Attribute VB_Name = "mdlVarQryNames"
Option Compare Database
Option Explicit

Public Const qTest = "qryTest"

Public Const qryDateEndregUd = "endRegUd"
Public Const qrySpecComplect = "specComplectTextDescr"
Public Const qryTemplate = "templateQuery"
'editing bases after import
Public Const qryArticul = "articul"
Public Const qryArticulSplit = "articulSplit"
Public Const qryAuthor = "author"
Public Const qryChangesRegUd = "changesRegUd"
Public Const qryChangesRegUdTo1C = "changesRegUdTo1C"
Public Const qryCountPlaceis = "countPlaceis"
Public Const qryDescr = "descr"
Public Const qryDoubleRows = "doubleRows"
Public Const qrydoubleRowsDel = "doubleRowsDel"
Public Const qryExportTo1C = "@1C"
Public Const qryFolders = "folders"
Public Const qryFTSpp312 = "FTSpp312"
Public Const qryGetCsvDs = "csvDS"
Public Const qryGetCsvRu = "csvRU"
Public Const qryGetCsvSs = "csvSS"
Public Const qryGetCsvUtsi = "csvUtsi"
Public Const qryGetDS = "getDS"
Public Const qryGetRu = "getRu"
Public Const qryGetRuNotUpdated = "getRuNotUpdated"
Public Const qryGetSS = "getSS"
Public Const qryGetUtsi = "getUtsi"
Public Const qryLenSizeFld = "lenSizeFld"
Public Const qryListKeysTableName = "listKeysRegUd"
Public Const qryLinksDoublesRUsearch = "linksDoublesRUsearch"
Public Const qryLinksRUsearch = "linksRUsearch"
Public Const qryMain = "main"
Public Const qryMain1 = "main1"
'Public Const qryMain2 = "main2"
Public Const qryMainBaseToDescr = "MainBaseToDescr"
Public Const qryMainBaseToRegUd1C = "MainBaseToRegUd1C"
Public Const qryMainBaseDelRow = "MainBaseDelRow"
Public Const qryMainDBendSsDs = "mainDbEndSsDs"
Public Const qryMedCod = "MedCod_174"
Public Const qryMedCodInBase = "MedCod_1C"
Public Const qryOkpRegUd = "okpRegUd"
Public Const qryOpenMainNomenclature = "openMainNomenclature"
Public Const qryPathRegUd = "pathRegUd"
Public Const qryPathSertificates = "pathSertificates"
Public Const qryPathUtsi = "pathUtsi"
Public Const qryPost = "post"
Public Const qryPP1042 = "pp1042"
Public Const qryPP688 = "pp688"
Public Const qryReceipts = "receipts"
Public Const qryReceiptsRegUd = "receiptsRegUd"
Public Const qryRegUdDelRow = "qryRegUdDelRow"
Public Const qryRegUdDescr = "regUdDescr"
Public Const qryProduce = "produce"
Public Const qryRegUdSearch = "regUdSearch"
Public Const qryRegUdSearch1 = "regUdSearch1"
Public Const qryRegUdSearch2 = "regUdSearch2"
Public Const qrySeller = "seller"
Public Const qrySizeBrutto = "sizeBrutto"
Public Const qrySizeDescr = "sizeDescr"
Public Const qrySpecComplData = "specComplData"
Public Const qrySpecComplResult = "specComplResult"
Public Const qrySplitOtkaz = "otkaz"
Public Const qrySplitRow = "splitRow"
Public Const qryTNVED = "tnved"
Public Const qryTNVED1 = "tnved1"
Public Const qryTNVED2 = "tnvedAll"
Public Const qryUPDATE = "UPDATEpathNum"

' form SsDs queries
Public Const qryFromLinksToScansSertificates = "fromLinksToScansSertificates"
Public Const qryEndSsDs = "endSsDs"
Public Const qryEndUtsi = "endUtsi"
Public Const qryEndDsSsLeftover = "endDsSsLeftover"
Public Const qryMainDs = "mainDs"
Public Const qryMainSs = "mainSs"
Public Const qryMainUtsi = "mainUtsi"
Public Const qryEndDsTo1C = "endDs_1C"
Public Const qryEndSsTo1C = "endSs_1C"
Public Const qryEndUtsiTo1C = "endUtsi_1C"
Public Const qryToSsDs = "toSsDs"
Public Const qryToUtsi = "toUtsi"
Public Const qrySsDsMovies = "SsDsMovies"
Public Const qrySsDsPostDs = "SsDsPostDs"

' KA '
Public Const qryKaNomenclature = "kaNomenclature"
Public Const qryKaJoinMain = "kaJoinMain"
Public Const qryKaRightMain = "kaRightMain"
